name = "zeezoo-washme"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "index.js"
build = { command = "echo 'No build needed'" }
compatibility_date = "2026-05-16"

[env.production]
name = "zeezoo-washme"
